[[redirects]]
  from = "/validation-key.txt"
  to = "/validation-key.txt"
  status = 200
  force = true
# Netlify Configuration for Purple

[build]
  command = "npm run build"
  publish = "public"

# Optional: Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
